import React from 'react'
import Select from 'react-select'

const optionsS = [
  { value: 'CAN', label: 'Canadian Studies'},
  { value: 'CHE', label: 'Chemical Engineering'},
  { value: 'CHY', label: 'Chemistry'},
  { value: 'CHF', label: 'Child Development and Family Relations'},
  { value: 'CHI', label: 'Chinese'},
  { value: 'CIE', label: 'Civil and Environmental Engineering'},
  { value: 'CET', label: 'Construction Engineering Technology'},
  { value: 'CLA', label: 'Classics'},
  { value: 'CSD', label: 'Communication Sciences and Disorders'},
  { value: 'CCE', label: 'Computer Engineering'},
  { value: 'COS', label: 'Computer Science'},
  { value: 'CET', label: 'Construction Engineering Technology'},
  { value: 'ERS', label: 'Earth Sciences'},
  { value: 'EES', label: 'Ecology and Environmental Sciences'},
  { value: 'ECO', label: 'Economics'},
  { value: 'ECE', label: 'Electrical Engineering'},
  { value: 'EET', label: 'Electrical Engineering Technology'},
  { value: 'EHD', label: 'Elementary Education'},
  { value: 'EPH', label: 'Engineering Physics'},
  { value: 'ENG', label: 'English'},
  { value: 'EHO', label: 'Environmental Horticulture'},
  { value: 'FEC', label: 'Financial Economics'},
  { value: 'FSN', label: 'Food Science and Human Nutrition'},
  { value: 'FBB', label: 'Forest Operations, Bioproducts, and Bioenergy'},
  { value: 'SFR', label: 'Forestry'},
  { value: 'FRE', label: 'French'},
  { value: 'HTY', label: 'History'},
  { value: 'HDC', label: 'Human Dimensions of Climate Change'},
  { value: 'INT', label: 'Interdisciplinary Studies'},
  { value: 'INA', label: 'International Affairs'},
  { value: 'JSM', label: 'Journalism'},
  { value: 'KPE', label: 'Kinesiology and Physical Education'},
  { value: 'SMS', label: 'Marine Science'},
  { value: 'MAT', label: 'Mathematics'},
  { value: 'MEE', label: 'Mechanical Engineering'},
  { value: 'MET', label: 'Mechanical Engineering Technology'},
  { value: 'MDS', label: 'Media Studies'},
  { value: 'MLS', label: 'Medical Laboratory Sciences'},
  { value: 'BMB', label: 'Microbiology'},
  { value: 'MCB', label: 'Molecular and Cellular Biology'},
  { value: 'MUS', label: 'Music'},
  { value: 'MED', label: 'Music Education'},
  { value: 'MPF', label: 'Music Performance'},
  { value: 'NMD', label: 'New Media'},
  { value: 'NUR', label: 'Nursing'},
  { value: 'SFR ', label: 'Parks, Recreation and Tourism'},
  { value: 'PHI', label: 'Philosophy'},
  { value: 'PHY', label: 'Physics'},
  { value: 'POS', label: 'Political Science'},
  { value: 'PSY', label: 'Psychology'},
  { value: 'FRE', label: 'Romance Languages'},
  { value: 'EHD', label: 'Secondary Education'},
  { value: 'SWK', label: 'Social Work'},
  { value: 'SOC', label: 'Sociology'},
  { value: 'SPA', label: 'Spanish'},
  { value: 'SRT', label: 'Studio Art'},
  { value: 'SVT', label: 'Surveying Engineering Technology'},
  { value: 'PSE', label: 'Sustainable Agriculture'},
  { value: 'THE', label: 'Theatre'},
  { value: 'UST', label: 'University Studies'},
  { value: 'WLE', label: 'Wildlife Ecology'},
  { value: 'WGS', label: 'Women’s, Gender, and Sexuality Studies'},
  { value: 'ZOO', label: 'Zoology'}
]

const optionsT = [
    { value: 'Mo9', label: 'Monday 9:00am - 10:00am' },
    { value: 'Mo10', label: 'Monday 10:00am - 11:00am' },
    { value: 'Mo11', label: 'Monday 11:00am - 12:00pm' },
    { value: 'Mo12', label: 'Monday 12:00pm - 1:00pm' },
    { value: 'Mo1', label: 'Monday 1:00pm - 2:00pm' },
    { value: 'Mo2', label: 'Monday 2:00pm - 3:00pm' },
    { value: 'Mo3', label: 'Monday 3:00pm - 4:00pm' },
    { value: 'Mo4', label: 'Monday 4:00pm - 5:00pm' },

    { value: 'Tu9', label: 'Tuesday 9:00am - 10:00am' },
    { value: 'Tu10', label: 'Tuesday 10:00am - 11:00am' },
    { value: 'Tu11', label: 'Tuesday 11:00am - 12:00pm' },
    { value: 'Tu12', label: 'Tuesday 12:00pm - 1:00pm' },
    { value: 'Tu1', label: 'Tuesday 1:00pm - 2:00pm' },
    { value: 'Tu2', label: 'Tuesday 2:00pm - 3:00pm' },
    { value: 'Tu3', label: 'Tuesday 3:00pm - 4:00pm' },
    { value: 'Tu4', label: 'Tuesday 4:00pm - 5:00pm' },

    { value: 'We9', label: 'Wednesday 9:00am - 10:00am' },
    { value: 'We10', label: 'Wednesday 10:00am - 11:00am' },
    { value: 'We11', label: 'Wednesday 11:00am - 12:00pm' },
    { value: 'We12', label: 'Wednesday 12:00pm - 1:00pm' },
    { value: 'We1', label: 'Wednesday 1:00pm - 2:00pm' },
    { value: 'We2', label: 'Wednesday 2:00pm - 3:00pm' },
    { value: 'We3', label: 'Wednesday 3:00pm - 4:00pm' },
    { value: 'We4', label: 'Wednesday 4:00pm - 5:00pm' },

    { value: 'Th9', label: 'Thursday 9:00am - 10:00am' },
    { value: 'Th10', label: 'Thursday 10:00am - 11:00am' },
    { value: 'Th11', label: 'Thursday 11:00am - 12:00pm' },
    { value: 'Th12', label: 'Thursday 12:00pm - 1:00pm' },
    { value: 'Th1', label: 'Thursday 1:00pm - 2:00pm' },
    { value: 'Th2', label: 'Thursday 2:00pm - 3:00pm' },
    { value: 'Th3', label: 'Thursday 3:00pm - 4:00pm' },
    { value: 'Th4', label: 'Thursday 4:00pm - 5:00pm' },

    { value: 'Fr9', label: 'Friday 9:00am - 10:00am' },
    { value: 'Fr10', label: 'Friday 10:00am - 11:00am' },
    { value: 'Fr11', label: 'Friday 11:00am - 12:00pm' },
    { value: 'Fr12', label: 'Friday 12:00pm - 1:00pm' },
    { value: 'Fr1', label: 'Friday 1:00pm - 2:00pm' },
    { value: 'Fr2', label: 'Friday 2:00pm - 3:00pm' },
    { value: 'Fr3', label: 'Friday 3:00pm - 4:00pm' },
    { value: 'Fr4', label: 'Friday 4:00pm - 5:00pm' },
    
  ]

const SubjectSelect = () => (
  <Select isMulti options={optionsS} />
)

const TimeSelect = () => (
    <Select isMulti options={optionsT} />
  )

export{ SubjectSelect, TimeSelect }